[pytest]
markers =
    login: login module tests
    change: change module tests
    smoke: smoke tests
    regression: regression tests
    cart: add to car tests
    checkout: checkout module tests
    inventory : inventory module tests
    logout: logout module tests
    failure: failed cases tests
    ui: ui tests
    api: api tests
    addopts = --alluredir=reports/allure-results