name: UI Automation CI

on:
  push:
    branches: [ main ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  --alluredir=reports/allure-results --clean-alluredir
        # pytest -m "not failure" --alluredir=reports/allure-results

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
        tar -zxvf allure-2.29.0.tgz
        sudo mv allure-2.29.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate Allure Report
      run: |
        allure generate reports/allure-results --clean -o reports/allure-report

    - name: Generate Analytics Dashboard
      run: |
        python utils/analytics_dashboard.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: automation-reports
        path: |
          reports/allure-report
          reports/*.csv
          reports/*.html

    - name: Commit reports
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add reports/*.csv
        git add reports/*.html
        git add reports/*.json

        git commit -m "update automation analytics reports" || echo "No changes"
        git push

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports