name: UI Automation CI

on:
  push:
    branches: [ main ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        rm -rf reports/allure-results
        pytest -m "not failure" --alluredir=reports/allure-results

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
        tar -zxvf allure-2.29.0.tgz
        sudo mv allure-2.29.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate Allure Report
      run: |
        allure generate reports/allure-results --clean -o reports/allure-report
        
    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports/allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-report